### ISSUE TITLE
antd-theme-generator@1.2.3 throws error

### ISSUE THREAD

**Issue by afc163** [mzohaibqc/antd-theme-generator#42]
```
git clone git@github.com:ant-design/ant-design.git
cd ant-design
npm i
npm run color-less
```

<img width="1247" alt="image" src="https://user-images.githubusercontent.com/507615/82311328-23d01500-99f8-11ea-96fb-448c90313d81.png">

```
> antd@4.2.4 color-less /Users/afc163/Projects/ant-design
> node ./scripts/generate-color-less

🔩 less render start!
error TypeError: Cannot read property 'slice' of undefined
    at generateTheme (/Users/afc163/Projects/ant-design/node_modules/antd-theme-generator/index.js:337:46)
    at Object.<anonymous> (/Users/afc163/Projects/ant-design/scripts/generate-color-less.js:49:1)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11
[LessError: JavaScript evaluation error: 'ReferenceError: colorPalette is not defined'] {
  message: "JavaScript evaluation error: 'ReferenceError: colorPalette is not defined'",
  stack: undefined,
  type: 'Syntax',
  filename: '/Users/afc163/Projects/ant-design/node_modules/antd-pro-merge-less/.temp/pro.less',
  index: 561955,
  line: 26146,
  column: 0,
  callLine: NaN,
  callExtract: undefined,
  extract: [
    '// ========================== Tree ==========================',
    '.antTreeFn(@select-tree-prefix-cls);',
    ''
  ]
}
```

`1.2.2` works fine.

**Comment by mzohaibqc** [comment]
@afc163 I ran it locally and was able to reproduce it. There is missing parameter `antDir: path.join(__dirname, '../node_modules/antd')` in options which I added 

```
const options = {
  antDir: path.join(__dirname, '../node_modules/antd'),
  stylesDir: path.join(__dirname, '../site/theme/static'),
  antdStylesDir: path.join(__dirname, '../components'),
  varFile: path.join(__dirname, '../components/style/themes/default.less'),
  mainLessFile: path.join(__dirname, '../site/theme/static/index.less'),
  themeVariables: ['@primary-color'],
  outputFilePath: path.join(__dirname, '../_site/color.less'),
};

generateTheme(options);
```

But now I am getting for `antd-pro-merge-less` since some files are using some less variables which are not imported e.g.

![image](https://user-images.githubusercontent.com/13637803/82331783-0605ae80-99fe-11ea-9bd3-75124b1db959.png)

**Comment by afc163** [comment]
No error throw when using `antd-theme-generator@1.2.2` even without `antDir`. Is [V2](https://github.com/mzohaibqc/antd-theme-generator/commit/53c219ae2efbbcc71e38dbf9d3b386f7e7c79cc1) being released as `1.2.3` unexpectedly?

**Comment by mzohaibqc** [comment]
@afc163 `antDir` parameter was always there since 1st version as you can see here

https://www.npmjs.com/package/antd-theme-generator/v/1.0.0

You are right that is was working before v1.2.3 without `antDir` but in order to fix some bugs, it is required now.

But even you comment `generateTheme(options);` line, it is still breaking as I added a screenshot above . `antd-pro-merge-less` is breaking since there is no variables imported referenced in that file e.g. `@site-text-color` is not imported here https://github.com/ant-design/ant-design/blob/master/site/theme/static/demo.less

@chenshuai2144 Can tell, how `antd-pro-merge-less` works

![image](https://user-images.githubusercontent.com/13637803/82348722-af569f80-9a12-11ea-802a-9f45e26358a7.png)

**Comment by chenshuai2144** [comment]
antd-pro-merge-less will create file in _site folder.
you  can create _site folder, will fix this error

**Comment by afc163** [comment]
Problem still exists in https://github.com/ant-design/ant-design/pull/24324, `antd-pro-merge-less` has fixed it's problem.

**Comment by mzohaibqc** [comment]
@afc163 Kindly have a look at this PR and merge it if looks good to you.

https://github.com/ant-design/ant-design/pull/24450

**Comment by mzohaibqc** [comment]
> @afc163 Kindly have a look at this PR and merge it if looks good to you.
> 
> [ant-design/ant-design#24450](https://github.com/ant-design/ant-design/pull/24450)

Thanks, @afc163 for merging this PR. Let me know if you find some primary color not being updated on selecting different primary color from footer primary color selector.
