### ISSUE TITLE
Why is it invalid to use CSS custom variables

### ISSUE THREAD

**Issue by fariellany** [mzohaibqc/antd-theme-generator#51]
**Describe the bug**
Describe your bug in English language
Why is it invalid to use CSS custom variables
**Show your code**
Show your `config-overrides.js` file and styles folder structure

// variables.less
@import "~antd/lib/style/themes/default.less";

@link-color: #313653;
@primary-color: #313653;

:root {
    --PC: @primary-color;
}

//other.less

 .add {
        color: var(--PC);
    }

why invalid？？？

**Screenshots**

**Version**
Which version is installed in your application? Try using the latest version, that may help

**Comment by 520Yanxiaofei** [comment]
你好小姐姐，请问你解决了吗

**Comment by fariellany** [comment]
> 你好小姐姐，请问你解决了吗

你也遇到这个问题了吗

**Comment by mzohaibqc** [comment]
I tried and it worked without an issue

![image](https://user-images.githubusercontent.com/13637803/86446482-7443cd80-bd2d-11ea-8726-f41df1429ff6.png)

But since this is not a less variable, so it will not be handled by theme plugin and will not get updated when user will update primary or any assigned variable color.

![image](https://user-images.githubusercontent.com/13637803/86446700-bb31c300-bd2d-11ea-90ec-5e1b158b35ea.png)


Here is commit for changes and it worked

https://github.com/mzohaibqc/antd-theme-generator/commit/8f4bbd49a14acc0a32a35beb1f61acd38ef73e00

**Comment by hekb001** [comment]
我也遇到了同样的问题 ，root 里面定义的自定义样式没有打包进去，查看源码才知道，安装的最新版本，只会通过key:value，等方式覆盖antd默认样式，并不会追加。老版本1.1.9是直接追加上去，可以把root里面的加进去。
