### ISSUE TITLE
less-bundle-promise报错

### ISSUE THREAD

**Issue by xiaochena** [mzohaibqc/antd-theme-generator#96]
我不太清楚具体发生了什么、但是当我将antd升级为4.17.0-alpha.5后发生了以下问题
```
 DeprecationWarning: Invalid 'main' field in 'E:\coProject\sales-front\node_modules\less-bundle-promise\package.json' of 'build/index.js'. Please either fix that or report it to the module author
(Use `node --trace-deprecation ...` to show where the warning was created)
node:internal/fs/utils:343
    throw err;
    ^

Error: ENOENT: no such file or directory, open 'E:\coProject\sales-front\node_modules\antd\lib\style\themes\@{root-entry-name}.less'
```
似乎less-bundle-promise发生了问题

**Comment by daichuqi** [comment]
+1

**Comment by daichuqi** [comment]
I believe what's happening is that in 4.17.0 Antd added a less variable called **root-entry-name** in  /lib/style/themes/index.less. And Antd expect users to define this variable through webpack configuration and when less-bundle-promise is trying to read this this index.less the root-entry-name is not defined anywhere and throw an error

**Comment by liukewia** [comment]
Hi, this problem has been there since antd v4.17.x, and there has been discussions like [https://github.com/ant-design/ant-design-pro/issues/9082#issuecomment-925609753](url).

The file `node_modules/antd/lib/style/themes/index.less` now should be rewritten by some webpack configurations. However, the `npm run color.js` command runs before the webpack starts.

The temporary solution is to change the content of file `node_modules/antd/lib/style/themes/index.less` from `@import './@{root-entry-name}.less';` back to the previous content `@import './default.less';`.

If one wish to do this change automatically, they can put this inside `color.js`.
```js
const fs = require('fs');
const _root = path.join(__dirname, './'); // if the file is in project's root path.

fs.readFile(
  path.join(_root, '/node_modules/antd/lib/style/themes/index.less'),
  'utf8',
  function (err, files) {
    var result = files.replace(/@\{root-entry-name\}/g, 'default');
    fs.writeFile(
      path.join(_root, '/node_modules/antd/lib/style/themes/index.less'),
      result,
      'utf8',
      function (err) {
        if (err) {
          console.log(err);
        }
      },
    );
  },
);
```

**Comment by wkylin** [comment]
> 

Thanks

But there's another problem

![image](https://user-images.githubusercontent.com/1208330/146285283-c9e987d0-bf36-4ee1-bd75-dbda4d6df40e.png)

**Comment by mzohaibqc** [comment]
This issue has been fixed in 
`less-bundle-promise@1.0.11`
`antd-theme-generator@1.2.11`
